# Generated by Django 3.1.1 on 2020-10-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20200930_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy_rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_rank_name', models.TextField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chair_name', models.TextField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Course_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type_name', models.TextField(max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_text', models.TextField(max_length=511)),
                ('course_name', models.TextField(max_length=511)),
                ('info', models.TextField(max_length=1023)),
            ],
        ),
        migrations.CreateModel(
            name='Ext_Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=45)),
                ('surname', models.TextField(max_length=45)),
                ('middle_name', models.TextField(max_length=45)),
                ('work_position', models.TextField(max_length=255)),
                ('diplom', models.TextField(max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='PHD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phd_name', models.TextField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Realization_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realization_form_name', models.TextField(max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.TextField(max_length=511)),
            ],
        ),
    ]
