# Generated by Django 3.1.2 on 2020-11-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0005_remove_chair_chair_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dicts',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('dicts_name', models.CharField(choices=[(1, 'ВУЗ'), (2, 'Кафедра'), (3, 'Учёная степень'), (4, 'Учёное звание'), (5, 'Форма обучения'), (6, 'Форма реализации')], default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ID',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('input', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='chair',
            name='chair_name',
            field=models.CharField(choices=[(12, 'ФОВ'), (13, 'ФСиАСУ'), (14, 'ФПВО'), (15, 'ФВР'), (16, 'ФПМИ'), (17, 'ММФ'), (18, 'ГФ'), (19, 'БФ'), (20, 'РАФ'), (21, 'ФФ'), (22, 'ХФ'), (23, 'ФМО'), (24, 'АТФ'), (25, 'АФ'), (26, 'ВТФ'), (27, 'СТФ'), (28, 'СФ'), (29, 'ВФ'), (30, 'ФКСиС'), (31, 'ФИТУ'), (32, 'ФРЭ'), (33, 'ФКП'), (34, 'ИЭФ'), (35, 'ИФ'), (36, 'ФМФ'), (37, 'ФБРФ'), (38, 'ФДО'), (39, 'ЛХФ'), (40, 'ФИТ'), (41, 'ФХТТ'), (42, 'ФТОВ'), (43, 'ВМФ'), (44, 'ЛФ'), (45, 'СФ'), (46, 'ФФ'), (47, 'СПФМВС'), (48, 'СПФСИЕ'), (49, 'ФОФКТ'), (50, 'ФТГ')], default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='education',
            name='course_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='course_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academy_rank',
            name='academy_rank_name',
            field=models.CharField(choices=[(4, 'магистрант'), (5, 'аспирант'), (6, 'кандидат наук'), (7, 'доктор наук'), (8, 'отсутствует')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='course_type',
            name='course_type_name',
            field=models.CharField(choices=[(1, 'КПК'), (2, '5 месяцев'), (3, '8 месяцев'), (4, '9 месяцев'), (5, '2 года')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='course_name',
            field=models.TextField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='info',
            field=models.TextField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='university_text',
            field=models.TextField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='ext_students',
            name='diplom',
            field=models.TextField(blank=True, max_length=511, null=True),
        ),
        migrations.AlterField(
            model_name='ext_students',
            name='middle_name',
            field=models.TextField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ext_students',
            name='name',
            field=models.TextField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ext_students',
            name='surname',
            field=models.TextField(blank=True, max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='ext_students',
            name='work_position',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phd',
            name='phd_name',
            field=models.CharField(choices=[(10, 'кандидат наук'), (11, 'доктор наук'), (12, 'профессор'), (13, 'отсутствует')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='realization_form',
            name='realization_form_name',
            field=models.CharField(choices=[(1, 'один'), (2, 'два'), (3, 'три')], default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_name',
            field=models.CharField(choices=[(1, 'ВАРБ'), (2, 'БГУ'), (3, 'БГУИР'), (4, 'БНТУ'), (5, 'БГПУ'), (6, 'БГТУ'), (7, 'БГМУ'), (8, 'БГУФК')], default=None, max_length=100),
        ),
    ]
