# Generated by Django 3.1.2 on 2020-11-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0006_auto_20201130_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='add',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realization_form',
            name='realization_form_name',
            field=models.CharField(choices=[(1, 'научная статья'), (2, 'лекция'), (3, 'три')], default=None, max_length=100),
        ),
    ]
