# Generated by Django 3.1.2 on 2020-12-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0007_auto_20201130_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Context_Search',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fio', models.CharField(choices=[(1, 'Иванов Иван Иванович'), (5, 'Петров Петр Петрович'), (6, 'Сидоров Иван Петрович'), (14, 'Ивановский Иван Васильевич'), (15, 'Пупкин Василий Васильевич'), (17, 'Пупкин Василий Иванович'), (18, 'Кузнецов Александр Васильевич'), (19, 'Пупкин Александр Васильевич'), (21, 'Конь Иван Иванович'), (22, 'Конь Иван Иванович')], default=None, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='academy_rank',
            name='academy_rank_name',
            field=models.CharField(choices=[(4, 'магистрант'), (5, 'аспирант'), (6, 'кандидат наук'), (7, 'доктор наук'), (8, 'отсутствует')], default=(4, 'магистрант'), max_length=100),
        ),
        migrations.AlterField(
            model_name='chair',
            name='chair_name',
            field=models.CharField(choices=[(12, 'ФОВ'), (13, 'ФСиАСУ'), (14, 'ФПВО'), (15, 'ФВР'), (16, 'ФПМИ'), (17, 'ММФ'), (18, 'ГФ'), (19, 'БФ'), (20, 'РАФ'), (21, 'ФФ'), (22, 'ХФ'), (23, 'ФМО'), (24, 'АТФ'), (25, 'АФ'), (26, 'ВТФ'), (27, 'СТФ'), (28, 'СФ'), (29, 'ВФ'), (30, 'ФКСиС'), (31, 'ФИТУ'), (32, 'ФРЭ'), (33, 'ФКП'), (34, 'ИЭФ'), (35, 'ИФ'), (36, 'ФМФ'), (37, 'ФБРФ'), (38, 'ФДО'), (39, 'ЛХФ'), (40, 'ФИТ'), (41, 'ФХТТ'), (42, 'ФТОВ'), (43, 'ВМФ'), (44, 'ЛФ'), (45, 'СФ'), (46, 'ФФ'), (47, 'СПФМВС'), (48, 'СПФСИЕ'), (49, 'ФОФКТ'), (50, 'ФТГ')], default=(12, 'ФОВ'), max_length=100),
        ),
        migrations.AlterField(
            model_name='course_type',
            name='course_type_name',
            field=models.CharField(choices=[(1, 'КПК'), (2, 'стажировка'), (3, '8 месяцев'), (4, '9 месяцев'), (5, '2 года'), (6, 'тренинг')], default=(1, 'КПК'), max_length=100),
        ),
        migrations.AlterField(
            model_name='phd',
            name='phd_name',
            field=models.CharField(choices=[(10, 'кандидат наук'), (11, 'доктор наук'), (12, 'профессор'), (13, 'отсутствует')], default=(10, 'кандидат наук'), max_length=100),
        ),
        migrations.AlterField(
            model_name='realization_form',
            name='realization_form_name',
            field=models.CharField(choices=[(1, 'научная статья'), (2, 'лекция'), (3, 'тестовые задания'), (4, 'словарь терминов')], default=(1, 'научная статья'), max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_name',
            field=models.CharField(choices=[(1, 'ВАРБ'), (2, 'БГУ'), (3, 'БГУИР'), (4, 'БНТУ'), (5, 'БГПУ'), (6, 'БГТУ'), (7, 'БГМУ'), (8, 'БГУФК'), (9, 'ИНБ')], default=(1, 'ВАРБ'), max_length=100),
        ),
    ]
